 export const transletterate = (letter) => {
    switch(letter) {
        case 'а':
            return 'a';
        case 'А':
            return 'A';
        case 'б':
            return 'b';
        case 'Б':
            return 'B';
        case 'в':
            return 'v';
        case 'В':
            return 'V';
        case 'г':
            return 'g';
        case 'Г':
            return 'G';
        case 'д':
            return 'd';
        case 'Д':
            return 'D';
        case 'е':
            return 'e';
        case 'Е':
            return 'E';
        case 'ё':
            return 'yo';
        case 'Ё':
            return 'Yo';
        case 'ж':
            return 'zh';
        case 'Ж':
            return 'Zh';
        case 'з':
            return 'z';
        case 'З':
            return 'Z';
        case 'и':
            return 'i';
        case 'И':
            return 'I';
        case 'й':
            return 'y';
        case 'Й':
            return 'Y';
        case 'к':
            return 'k';
        case 'К':
            return 'K';
        case 'л':
            return 'l';
        case 'Л':
            return 'L';
        case 'м':
            return 'm';
        case 'М':
            return 'M';
        case 'н':
            return 'n';
        case 'Н':
            return 'N';
        case 'о':
            return 'o';
        case 'О':
            return 'O';
        case 'п':
            return 'p';
        case 'П':
            return 'P';
        case 'р':
            return 'r';
        case 'Р':
            return 'R';
        case 'с':
            return 's';
        case 'С':
            return 'S';
        case 'т':
            return 't';
        case 'Т':
            return 'T';
        case 'у':
            return 'u';
        case 'У':
            return 'U';
        case 'ф':
            return 'f';
        case 'Ф':
            return 'F';
        case 'х':
            return 'h';
        case 'Х':
            return 'H';
        case 'ц':
            return 'ts';
        case 'Ц':
            return 'Ts';
        case 'ч':
            return 'ch';
        case 'Ч':
            return 'Ch';
        case 'ш':
            return 'sh';
        case 'Ш':
            return 'Sh';
        case 'щ':
            return 'sch';
        case 'Щ':
            return 'Sch';
        case 'ъ':
            return '\'';
        case 'Ъ':
            return '\'';
        case 'ы':
            return 'i';
        case 'Ы':
            return 'I';
        case 'ь':
            return '\'';
        case 'Ь':
            return '\'';
        case 'э':
            return 'e';
        case 'Э':
            return 'E';
        case 'ю':
            return 'u';
        case 'Ю':
            return 'U';
        case 'я':
            return 'ya';
        case 'Я':
            return 'Ya';
        case '«':
            return '"';
        case '»':
            return '"';
        case '–':
            return '-';
        case '—':
            return '-';
        case '№':
            return '#';
        case '`':
            return '\'';
        default:
            return letter;
    }
}

export const isCyrillic = (letter) => {
    switch(letter) {
        case 'а':
            return true;
        case 'А':
            return true;
        case 'б':
            return true;
        case 'Б':
            return true;
        case 'в':
            return true;
        case 'В':
            return true;
        case 'г':
            return true;
        case 'Г':
            return true;
        case 'д':
            return true;
        case 'Д':
            return true;
        case 'е':
            return true;
        case 'Е':
            return true;
        case 'ё':
            return true;
        case 'Ё':
            return true;
        case 'ж':
            return true;
        case 'Ж':
            return true;
        case 'з':
            return true;
        case 'З':
            return true;
        case 'и':
            return true;
        case 'И':
            return true;
        case 'й':
            return true;
        case 'Й':
            return true;
        case 'к':
            return true;
        case 'К':
            return true;
        case 'л':
            return true;
        case 'Л':
            return true;
        case 'м':
            return true;
        case 'М':
            return true;
        case 'н':
            return true;
        case 'Н':
            return true;
        case 'о':
            return true;
        case 'О':
            return true;
        case 'п':
            return true;
        case 'П':
            return true;
        case 'р':
            return true;
        case 'Р':
            return true;
        case 'с':
            return true;
        case 'С':
            return true;
        case 'т':
            return true;
        case 'Т':
            return true;
        case 'у':
            return true;
        case 'У':
            return true;
        case 'ф':
            return true;
        case 'Ф':
            return true;
        case 'х':
            return true;
        case 'Х':
            return true;
        case 'ц':
            return true;
        case 'Ц':
            return true;
        case 'ч':
            return true;
        case 'Ч':
            return true;
        case 'ш':
            return true;
        case 'Ш':
            return true;
        case 'щ':
            return true;
        case 'Щ':
            return true;
        case 'ъ':
            return true;
        case 'Ъ':
            return true;
        case 'ы':
            return true;
        case 'Ы':
            return true;
        case 'ь':
            return true;
        case 'Ь':
            return true;
        case 'э':
            return true;
        case 'Э':
            return true;
        case 'ю':
            return true;
        case 'Ю':
            return true;
        case 'я':
            return true;
        case 'Я':
            return true;
        case '«':
            return true;
        case '»':
            return true;
        case '–':
            return true;
        case '—':
            return true;
        case '№':
            return true;
        case '`':
            return true;
        default:
            return false;
    }
}